/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestioncorredores.gui.carreras;

import gestioncorredores.dto.Carrera;
import gestioncorredores.logica.LogicaCarreras;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mad_d
 */
public class ListaCarreras extends javax.swing.JDialog {

    /**
     * Creates new form EditarCarrera
     */
    public ListaCarreras(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        tablasCarreras();
    }

    public void tablasCarreras() {

        DefaultTableModel dtmFin = new DefaultTableModel();
        DefaultTableModel dtmPen = new DefaultTableModel();
        dtmFin.setColumnIdentifiers(new String[]{"Nombre", "Lugar", "Fecha", "Numero Participantes"});
        dtmPen.setColumnIdentifiers(new String[]{"Nombre", "Lugar", "Fecha", "Numero Participantes"});

        List<Carrera> listaCarreras = LogicaCarreras.getListaCarreras();
        for (Carrera carrera : listaCarreras) {
            if (carrera.isCarreraAcabada()) {
                dtmFin.addRow(carrera.arrayDatosCarrera());
            } else {
                dtmPen.addRow(carrera.arrayDatosCarrera());
            }

        }

        jTableAcabada.setModel(dtmFin);
        jTableSinAcabar.setModel(dtmPen);

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAcabada = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableSinAcabar = new javax.swing.JTable();
        jButtonVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText(org.openide.util.NbBundle.getMessage(ListaCarreras.class, "ListaCarreras.jLabel1.text")); // NOI18N

        jTableAcabada.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableAcabada);
        if (jTableAcabada.getColumnModel().getColumnCount() > 0) {
            jTableAcabada.getColumnModel().getColumn(0).setHeaderValue(org.openide.util.NbBundle.getMessage(ListaCarreras.class, "ListaCarreras.jTableAcabada.columnModel.title0")); // NOI18N
            jTableAcabada.getColumnModel().getColumn(1).setHeaderValue(org.openide.util.NbBundle.getMessage(ListaCarreras.class, "ListaCarreras.jTableAcabada.columnModel.title1")); // NOI18N
            jTableAcabada.getColumnModel().getColumn(2).setHeaderValue(org.openide.util.NbBundle.getMessage(ListaCarreras.class, "ListaCarreras.jTableAcabada.columnModel.title2")); // NOI18N
            jTableAcabada.getColumnModel().getColumn(3).setHeaderValue(org.openide.util.NbBundle.getMessage(ListaCarreras.class, "ListaCarreras.jTableAcabada.columnModel.title3")); // NOI18N
        }

        jLabel2.setText(org.openide.util.NbBundle.getMessage(ListaCarreras.class, "ListaCarreras.jLabel2.text")); // NOI18N

        jTableSinAcabar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableSinAcabar);

        jButtonVolver.setText(org.openide.util.NbBundle.getMessage(ListaCarreras.class, "ListaCarreras.jButtonVolver.text")); // NOI18N
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonVolver)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 890, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addComponent(jScrollPane1)
                        .addComponent(jLabel1)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 252, Short.MAX_VALUE)
                .addComponent(jButtonVolver)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jButtonVolverActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(EditarCarrera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(EditarCarrera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(EditarCarrera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(EditarCarrera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                EditarCarrera dialog = new EditarCarrera(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableAcabada;
    private javax.swing.JTable jTableSinAcabar;
    // End of variables declaration//GEN-END:variables
}
