/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestioncorredores.gui.carreras;

import gestioncorredores.gui.carreras.tablemodels.ModificarCarrerasTableModel;
import gestioncorredores.logica.LogicaCarreras;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author mad_d
 */
public class ModificarBorrarCarreras extends javax.swing.JDialog {

    private LogicaCarreras logicaCarreras = new LogicaCarreras();
    private TableRowSorter<ModificarCarrerasTableModel> sorter;

    /**
     * Creates new form ModificarBorrarCarreras
     */
    public ModificarBorrarCarreras(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        jButtonEditar.setEnabled(false);
        rellenarTablaCarreras();
    }

    public void rellenarTablaCarreras() {

        ModificarCarrerasTableModel mct = new ModificarCarrerasTableModel(logicaCarreras.getListaCarreras());
        jTableCarreras.setModel(mct);

        sorter = new TableRowSorter<>(mct);
        jTableCarreras.setRowSorter(sorter);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCarreras = new javax.swing.JTable();
        jButtonVolver = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldLugar = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jSpinnerFecha = new javax.swing.JSpinner();
        jButtonBuscar = new javax.swing.JButton();
        jTextFieldBuscar = new javax.swing.JTextField();
        jButtonEliminar = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTableCarreras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableCarreras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableCarrerasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableCarreras);

        jButtonVolver.setText(org.openide.util.NbBundle.getMessage(ModificarBorrarCarreras.class, "ModificarBorrarCarreras.jButtonVolver.text")); // NOI18N
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });

        jLabel1.setText(org.openide.util.NbBundle.getMessage(ModificarBorrarCarreras.class, "ModificarBorrarCarreras.jLabel1.text")); // NOI18N

        jTextFieldNombre.setText(org.openide.util.NbBundle.getMessage(ModificarBorrarCarreras.class, "ModificarBorrarCarreras.jTextFieldNombre.text")); // NOI18N

        jLabel2.setText(org.openide.util.NbBundle.getMessage(ModificarBorrarCarreras.class, "ModificarBorrarCarreras.jLabel2.text")); // NOI18N

        jTextFieldLugar.setText(org.openide.util.NbBundle.getMessage(ModificarBorrarCarreras.class, "ModificarBorrarCarreras.jTextFieldLugar.text")); // NOI18N

        jLabel3.setText(org.openide.util.NbBundle.getMessage(ModificarBorrarCarreras.class, "ModificarBorrarCarreras.jLabel3.text")); // NOI18N

        jSpinnerFecha.setModel(new javax.swing.SpinnerDateModel());

        jButtonBuscar.setText(org.openide.util.NbBundle.getMessage(ModificarBorrarCarreras.class, "ModificarBorrarCarreras.jButtonBuscar.text")); // NOI18N
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        jTextFieldBuscar.setText(org.openide.util.NbBundle.getMessage(ModificarBorrarCarreras.class, "ModificarBorrarCarreras.jTextFieldBuscar.text")); // NOI18N

        jButtonEliminar.setText(org.openide.util.NbBundle.getMessage(ModificarBorrarCarreras.class, "ModificarBorrarCarreras.jButtonEliminar.text")); // NOI18N
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });

        jButtonEditar.setText(org.openide.util.NbBundle.getMessage(ModificarBorrarCarreras.class, "ModificarBorrarCarreras.jButtonEditar.text")); // NOI18N
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jButtonBuscar)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldBuscar))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldLugar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jSpinnerFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(265, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonEliminar)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonVolver)
                        .addGap(19, 19, 19))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 256, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldLugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jSpinnerFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonVolver)
                    .addComponent(jButtonBuscar)
                    .addComponent(jTextFieldBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEliminar)
                    .addComponent(jButtonEditar))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jButtonVolverActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        RowFilter<ModificarCarrerasTableModel, Integer> filtro = RowFilter.regexFilter(jTextFieldBuscar.getText(), 0);
        sorter.setRowFilter(filtro);
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        int seleccionado = jTableCarreras.convertRowIndexToModel(jTableCarreras.getSelectedRow());
        int resultado = JOptionPane.showConfirmDialog(this, "¿Eliminar carrera?", "Eliminar", JOptionPane.YES_NO_OPTION);
        if (resultado == JOptionPane.YES_OPTION) {
            logicaCarreras.getListaCarreras().remove(seleccionado);
        }

        rellenarTablaCarreras();
    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void jTableCarrerasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableCarrerasMouseClicked
        int seleccionado = jTableCarreras.convertRowIndexToModel(jTableCarreras.getSelectedRow());
        jButtonEditar.setEnabled(false);
        jTextFieldNombre.setText("");
        jTextFieldLugar.setText("");
        //jSpinnerFecha.setValue(null); vaciar valor del spinner???
        if (logicaCarreras.getListaCarreras().get(seleccionado).isCarreraAcabada() == false) {
            jTextFieldNombre.setText(logicaCarreras.getListaCarreras().get(seleccionado).getNombre());
            jTextFieldLugar.setText(logicaCarreras.getListaCarreras().get(seleccionado).getLugar());
            jSpinnerFecha.setValue(logicaCarreras.getListaCarreras().get(seleccionado).getFechaCarrera());
            jButtonEditar.setEnabled(true);
        }


    }//GEN-LAST:event_jTableCarrerasMouseClicked

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        int seleccionado = jTableCarreras.convertRowIndexToModel(jTableCarreras.getSelectedRow());
        int resultado = JOptionPane.showConfirmDialog(this, "¿Modificar carrera?", "Modificar", JOptionPane.YES_NO_OPTION);
        if (resultado == JOptionPane.YES_OPTION) {
            logicaCarreras.getListaCarreras().get(seleccionado).setNombre(jTextFieldNombre.getText());
            logicaCarreras.getListaCarreras().get(seleccionado).setLugar(jTextFieldLugar.getText());
            logicaCarreras.getListaCarreras().get(seleccionado).setFechaCarrera((Date)jSpinnerFecha.getValue());
        }
        rellenarTablaCarreras();
    }//GEN-LAST:event_jButtonEditarActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ModificarBorrarCarreras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ModificarBorrarCarreras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ModificarBorrarCarreras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ModificarBorrarCarreras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                ModificarBorrarCarreras dialog = new ModificarBorrarCarreras(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinnerFecha;
    private javax.swing.JTable jTableCarreras;
    private javax.swing.JTextField jTextFieldBuscar;
    private javax.swing.JTextField jTextFieldLugar;
    private javax.swing.JTextField jTextFieldNombre;
    // End of variables declaration//GEN-END:variables
}
